name: medically
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  google_fonts:
  font_awesome_flutter:
  bloc:
  flutter_bloc:
  conditional_builder:
  intl:
  dio:
  hexcolor:
  shared_preferences:
  smooth_page_indicator:
  fluttertoast:
  carousel_slider:
  flutter_staggered_animations:
  flutter_staggered_grid_view:
  flushbar:
  wiggly_circle:
  line_icons:
  flutter_icons:
  google_maps_flutter:
  geolocator:
  maps_launcher:
  url_launcher:
  flutter_signin_button:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_database:
  http:
  shimmer:
  flutter_typeahead:
  timeago:
  charts_flutter:
  flutter_svg:
  bubble_tab_indicator:
  fl_chart:
  connectivity:
  wifi_info_flutter:
#  image_picker:
#  firebase_storage:
  flutter_snake_navigationbar:
  responsive_builder:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: VEXA-
      fonts:
        - asset: assets/fonts/VEXA-.ttf
    - family: VEXA-thin
      fonts:
        - asset: assets/fonts/VEXA-thin.ttf
    - family: VEXA-ITALIC
      fonts:
         - asset: assets/fonts/VEXA-ITALIC.ttf
    - family: Tajawal-Bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: ElMessiri-Bold
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
    - family: ElMessiri-Medium
      fonts:
        - asset: assets/fonts/ElMessiri-Medium.ttf
    - family: ElMessiri-Regular
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
    - family: ElMessiri-SemiBold
      fonts:
        - asset: assets/fonts/ElMessiri-SemiBold.ttf




