part of 'doctors.dart';

List<DoctorsModel> doctorsModel = [
  // اسنان
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTf4c408/Profile/150/doctor-ahmed-abdallah-dentistry-2_20210630181043421.jpg",
      name: "د/ أحمد عبد الله",
      job: "دكتور اسنان متخصص في تجميل اسنان",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 2172,
      price: 150,
      phone: 19777,
      info:
          " ماجستير زراعة الاسنان من جامعة القاهرة (القصر العيني )، عضو الفريق العالمي لزراعة الاسنان،زميل الأكاديمية الامريكية لزراعة الاسنان",
      address: "ش جمال عبدالناصر",
      city: "العصافرة - الاسكندرية",
      day: "السبت - الجمعة",
      time: "من 10:30 صباحاً حتي 10:30 مساءاً"),
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT8d3df1/Profile/150/doctor-omar-eldidi-dentistry_20190804201909358.jpg",
      name: "د/ عمر الديدي",
      job: "اخصائي التركيبات الثابتة",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 346,
      price: 250,
      phone: 1977,
      info:
          " مجموعة من امهر اخصائين اطباء الاسنان كلن في تخصصه لكي يحصل العميل على اعلى مستويات الجودة من العلاج.قريبا فرع التجمع الخامس زراعة اسنان , تركيبات ثابتة و تجميليه , تبيض الاسنان , علاج جذور , طب اسنان الاطفال , علاج لثه و تنظيف الاسنان",
      address: "شارع عبد العزيز عيسى",
      city: "مدينة نصر - القاهرة",
      day: "السبت - الجمعة",
      time: "من الساعة 11 صباحاً حتي 8 مساءاً"),
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTc052d4/Profile/150/doctor-neviene-bishay-dentistry_20191128161948566.jpg",
      name: "د/ نيفين بشاي",
      job: "إستشارى جراحه ،تجميل و زراعه الاسنان",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 500,
      price: 300,
      phone: 19700,
      info:
          " د نيفين بشاي - استشاري جراحه وتجميل الاسنان و التركيبات الثابته و هي من أفضل ١٠ أطباء أسنان في مصر. لديها خبره أكثر من ١٥ عام في صناعه الابتسامه. تخرجت في ٢٠٠٣ و حصلت علي البورد الامريكي من كاليفورنيا في ٢٠٠٥ و قد حولت مسار أكثر من ١٠ آلاف إبتسامه الي إبتسامات مشرقه و جذابه. تتميز عياده الزمالك بموقعها المثالي في وسط القاهره. و لديها نخبة من أفضل الاطباء فى جميع تخصصات طب و تجميل الاسنان.",
      address: " شارع بهجت على",
      city: "الزمالك - القاهرة",
      day: "السبت - الجمعة",
      time: "من الساعة 6 مساءاً حتي 9:30 مساءاً"),
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTa28e6d/Profile/150/doctor-aly-ismail-el-tahan-dentistry_20200814170538086.jpg",
      name: "د/ علي إسماعيل الطحان",
      job: "دكتور اسنان متخصص في اسنان اطفال",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 450,
      price: 100,
      phone: 010620,
      info:
          " ١-اخصائي علاج الجذور (ماجيستير علاج الجذور- جامعه مصر الدوليه) ٢-ماچيستير جراحات تجميل الفم و اللثه و تجميل الاسنان بالليزر (جامعة أخن ألمانيا) ٣-عضو و زميل الجمعية العالمية لزراعة الاسنان ٤-عضو و زميل الجمعية الالمانية لزراعة الاسنان (جامعة جوته -فرانكفورت -المانيا) ٥-عضو الاكاديميه العالميه لليزر ٦- ٨ سنوات خبره في مجال طب الاسنان منذ عام ٢٠١٢",
      address: "ش طابا",
      city: "الزقايق - الشرقية",
      day: "السبت - الجمعة",
      time: "من الساعة 3 مساءاً حتي 10 مساءاً"),
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT8df726/Profile/150/mostafa--ahmed-abdelaal-dentistry_20200521133537941.jpg",
      name: "د/ مصطفى احمد عبدالعال",
      job: "أخصائي طب وتجميل الفم والاسنان",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 605,
      price: 200,
      phone: 15035,
      info:
          "أخصائي طب وتجميل الفم والاسنان",
      address: "شارع لبنان",
      city: "المهندسين - الجيزة",
      day: "السبت - الجمعة",
      time: "من الساعة 12 ظهراً حتي 7:30 مساءاً"),
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT7f7131/Profile/150/doctor-hesham-mohammed-elsharkha-dentistry_20191113125837067.jpg",
      name: "د/ هشام محمد الشرخة",
      job: "أخصائي طب الفم و علاج اللثة و زراعة الأسنان",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 780,
      price: 90,
      phone: 15035,
      info:
          "اخصائي علاج الجذور وتجميل الاسنان. علاج العصب في جلسه واحده باسخدام الميكروسكوب واحدث اجهزه علاج العصب",
      address: "شارع قناة السويس",
      city: "المنصورة - الدقهلية",
      day: "السبت - الجمعة",
      time: "من الساعة 4 م حتي 8 م "),
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTa997f0/Profile/150/doctor-mohamed--shaheen-dentistry_20210131025337350.jpg",
      name: "د/  محمد شاهين",
      job: "اخصائي علاج الجذور وتجميل الاسنان",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 500,
      price: 50,
      phone: 02180,
      info:
          " اخصائي علاج الجذور وتجميل الاسنان. علاج العصب في جلسه واحده باسخدام الميكروسكوب واحدث اجهزه علاج العصب",
      address: "ش جمال عبد الناصر",
      city: "سيدي بشر - الاسكندرية",
      day: "السبت - الجمعة",
      time: "من الساعة 11 ص حتي 11:30 م"),
  DoctorsModel(
      image:
          "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT6a03c27de2a067a0/Profile/150/doctor-mahmoud-ashoub_20200209112852599.jpg",
      name: "د/ محمود عشوب",
      job: "أستشارى تركيبات و تجميل الأسنان القصر العيني",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 2000,
      price: 200,
      phone: 03482,
      info:
          " أستشارى التركيبات الثابته و تجميل الأسنان بالقصر العيني - ماجستير و دكتوراه د التركيبات الثابتة و تجميل الاسنان بالقصر العيني - مدرس التركيبات الثابته وتجميل الاسنان بجامعة 6 اكتوبر-عضو الجمعيه الامريكيه لتجميل الاسنان بنيويورك",
      address: "المحور المركزي",
      city: "6 اكتوبر - الجيزة",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image:
      "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTd36157/Profile/150/doctor-mohamed-hamdy-dentistry_20200912211430607.jpg",
      name: "د/ محمد حمدي",
      job: "دكتور اسنان متخصص في تجميل اسنان",
      categoryName: "اسنان",
      rate: "4.5 / 5",
      numOfPatients: 1560,
      price: 150,
      phone: 1119,
      info:
      " دكتور محمد حمدي - زميل الكليه الملكيه بلندن",
      address: "الحي الثامن, اعلى اولاد رجب",
      city: "6اكتوبر - الجيزة",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  //جلدية و تناسلية
  DoctorsModel(
      image: "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT2ab6e2/Profile/150/center-misr-laser-dermatology_20190113113315554.jpg",
      name: "د/ محمد شلبي",
      job: "استشاري الامراض الجلديه و التناسليه و العقم والتجميل",
      categoryName: "جلدية و تناسلية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 120,
      phone: 018120,
      info:
          " خدمات العياده... الأمراض الجلديه.. التجميل.. العلاج بالليزر.. زراعة الشعر.. الأمراض التناسليه..",
      address: "شبين الكوم",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 5 م حتي 10 م"),
  DoctorsModel(
      image: "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT28b72398dad0a37a/Profile/150/basma-abdelrehem-dermatology_20210414203355688.jpg",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "جلدية و تناسلية",
      rate: "4.5 / 5",
      numOfPatients: 354,
      price: 105,
      phone: 16777,
      info:
          " اخصائي الامراض الجلديه والليزر والتجميل جامعة المنوفيه",
      address: " شارع الجلاء البحري",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 م حتي 5 م"),
  DoctorsModel(
      image: "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT8fd7d17017f6f53f/Profile/150/doctor-hosaam-hassan-plastic-surgery_20210703043710132.jpg",
      name: "د/ حسام حسن",
      job: "مدرس واستشاري جراحات التجميل والوجه والفكين",
      categoryName: "جلدية و تناسلية",
      rate: "4.5 / 5",
      numOfPatients: 147,
      price: 110,
      phone: 16777,
      info:
          " مدرس واستشاري جراحات التجميل والوجه والفكين دكتوراه جراحة التجميل زمالة جراحة التجميل والوجه والفكين جامعة أولسان كوريا الجنوبيه *جراحة تجميل الأنف *جراحة تجميل الوجه (الشفه الارنبيه،كسور الوجه والفكين،التشوهات الخلقيه) *جراحة تجميل الجفن -جراحة اليد *حرق *تشوه وجه الأطفال *نحت الجسم وجراحة السمنه *جراحة تجميل الأذن تجميل الجسم (شفط الدهون،شد الترهلات،نحت الجسم) تجميل الثدي (تصغير وتكبير وشد الثدي)",
      address: "ميدان شرف - برج الديوان",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الاثنين - الاربعاء",
      time: "من الساعة 1 ظهراً حتي 3 م"),
  DoctorsModel(
      image: "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTef15e0/Profile/150/doctor-ahmed-fergany-plastic-surgery_20190219165111871.jpg",
      name: "د/ احمد فرجاني",
      job: "استشارى جراحة التجميل والليزر",
      categoryName: "جلدية و تناسلية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 125,
      phone: 16777,
      info:
          " استشاري جراحة التجميل والليزر -عضو الجمعية المصرية لجراحة التجميل - عضو الجمعية الدولية لجراحة التجميل - عضو الجمعية العلمية السعودية لجراحة التجميل والحروق",
      address: " ميدان شرف _ امام البنزينة",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTc98b3e/Profile/150/doctor-manar-khater-plastic-surgery_20201104182013264.jpg",
      name: "د/ منار خاطر",
      job: "أخصائي جراحة التجميل والحروق",
      categoryName: "جلدية و تناسلية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 150,
      phone: 16777,
      info:
          " أخصائية جراحات التجميل والحروق وجراحات الوجه والفكين وجراحات اليد .... حقن بوتوكس وفيلر وتقشير للبشره وبلازما للشعر والوجه ** ماجستير جراحات التجميل والحروق مستشفيات جامعه القاهره ** اخصائى جراحات التجميل والحروق بمستشفى العربى ** اخصائى جراحات التجميل والحروق بمستشفى الطلبه جامعه المنوفيه ** حاصله على تدريب فى الطب التجميلي والليزر بأكاديمية مصر الدوليه وجامعه عين شمس ** عضو بالاكاديمية المصريه للجمال ** عضو بالجمعية المصريه للتعليم الطبى المستمر",
      address: "٦٠ شارع الخليفة المأمون",
      city: "مصر الجديدة - القاهرة",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENT5a0d11/Profile/150/doctor-hanan-dawoud-plastic-surgery_20210112155822865.jpg",
      name: "د/ محمود صبري صالح",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جلدية و تناسلية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع الجيش",
      city: "منوف - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://cdn-dr-images.vezeeta.com/Assets/Images/SelfServiceDoctors/ENTffdeb7/Profile/150/doctor-sally-salah-dermatology_20190404121108201.jpg",
      name: "د/ محمود صبري صالح",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جلدية و تناسلية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع الجيش",
      city: "منوف - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),

  //جراحة مخ و أعصاب
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16019.png",
      name: "د/ محمد السعيد لاشين",
      job: "دكتور مخ واعصاب",
      categoryName: "جراحة مخ و أعصاب",
      rate: "4 / 5",
      numOfPatients: 300,
      price: 120,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "ميدان شرف",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 4 عصراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16041.png",
      name: "د/ محمد السعيد لاشين",
      job: "دكتور مخ واعصاب",
      categoryName: "جراحة مخ و أعصاب",
      rate: "4 / 5",
      numOfPatients: 300,
      price: 120,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "ميدان شرف",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 4 عصراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16019.png",
      name: "د/ محمد السعيد لاشين",
      job: "دكتور مخ واعصاب",
      categoryName: "جراحة مخ و أعصاب",
      rate: "4 / 5",
      numOfPatients: 300,
      price: 120,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "ميدان شرف",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 4 عصراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16019.png",
      name: "د/ محمد السعيد لاشين",
      job: "دكتور مخ واعصاب",
      categoryName: "جراحة مخ و أعصاب",
      rate: "4 / 5",
      numOfPatients: 300,
      price: 120,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "ميدان شرف",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 4 عصراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16019.png",
      name: "د/ محمد السعيد لاشين",
      job: "دكتور مخ واعصاب",
      categoryName: "جراحة مخ و أعصاب",
      rate: "4 / 5",
      numOfPatients: 300,
      price: 120,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "ميدان شرف",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 4 عصراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16019.png",
      name: "د/ محمد السعيد لاشين",
      job: "دكتور مخ واعصاب",
      categoryName: "جراحة مخ و أعصاب",
      rate: "4 / 5",
      numOfPatients: 300,
      price: 120,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "ميدان شرف",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 4 عصراً"),
  // جراحة مسالك بولية
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16041.png",
      name: "د/ محمد يسري أبوزيد",
      job: "أخصائي جراحات العظام و المفاصل و العمود الفقري",
      categoryName: "جراحة مسالك بولية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 85,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع كلية الطب",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16041.png",
      name: "د/ محمد يسري أبوزيد",
      job: "أخصائي جراحات العظام و المفاصل و العمود الفقري",
      categoryName: "جراحة مسالك بولية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 85,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع كلية الطب",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16041.png",
      name: "د/ محمد يسري أبوزيد",
      job: "أخصائي جراحات العظام و المفاصل و العمود الفقري",
      categoryName: "جراحة مسالك بولية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 85,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع كلية الطب",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16041.png",
      name: "د/ محمد يسري أبوزيد",
      job: "أخصائي جراحات العظام و المفاصل و العمود الفقري",
      categoryName: "جراحة مسالك بولية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 85,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع كلية الطب",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16041.png",
      name: "د/ محمد يسري أبوزيد",
      job: "أخصائي جراحات العظام و المفاصل و العمود الفقري",
      categoryName: "جراحة مسالك بولية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 85,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع كلية الطب",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16041.png",
      name: "د/ محمد يسري أبوزيد",
      job: "أخصائي جراحات العظام و المفاصل و العمود الفقري",
      categoryName: "جراحة مسالك بولية",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 85,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع كلية الطب",
      city: "شبين الكوم - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  // اطفال
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16038.png",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "اطفال",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 110,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع البرقي",
      city: "بركةالسبع - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16038.png",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "اطفال",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 110,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع البرقي",
      city: "بركةالسبع - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16038.png",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "اطفال",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 110,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع البرقي",
      city: "بركةالسبع - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16038.png",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "اطفال",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 110,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع البرقي",
      city: "بركةالسبع - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16038.png",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "اطفال",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 110,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع البرقي",
      city: "بركةالسبع - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16038.png",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "اطفال",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 110,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع البرقي",
      city: "بركةالسبع - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16038.png",
      name: "د/ بسمه عبدالرحيم",
      job: "اخصائي الامراض الجلديه والليزر والتجميل",
      categoryName: "اطفال",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 110,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "شارع البرقي",
      city: "بركةالسبع - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  // جراحة عظام
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/doctor_PNG16018.png",
      name: "د/ عادل علام",
      job: "أخصائي طب الأطفال و حديثي الولادة",
      categoryName: "جراحة عظام",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "السوق التجاري المنطقة الرابعة",
      city: "السادات - المنوفية",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  //نساء و توليد
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "دكتور انف واذن وحنجرة",
      categoryName: "نساء و توليد",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "دكتور انف واذن وحنجرة",
      categoryName: "نساء و توليد",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "دكتور انف واذن وحنجرة",
      categoryName: "نساء و توليد",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "دكتور انف واذن وحنجرة",
      categoryName: "نساء و توليد",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "دكتور انف واذن وحنجرة",
      categoryName: "نساء و توليد",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "دكتور انف واذن وحنجرة",
      categoryName: "نساء و توليد",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "دكتور انف واذن وحنجرة",
      categoryName: "نساء و توليد",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),

  //جراحة أنف و أذن
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "قلـب و أوعية دموية",
      categoryName: "جراحة أنف و أذن",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "قلـب و أوعية دموية",
      categoryName: "جراحة أنف و أذن",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "قلـب و أوعية دموية",
      categoryName: "جراحة أنف و أذن",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "قلـب و أوعية دموية",
      categoryName: "جراحة أنف و أذن",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "قلـب و أوعية دموية",
      categoryName: "جراحة أنف و أذن",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "قلـب و أوعية دموية",
      categoryName: "جراحة أنف و أذن",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
  DoctorsModel(
      image: "https://pngimg.com/uploads/doctor/small/doctor_PNG16022.png",
      name: "د/ باسم سويد",
      job: "قلـب و أوعية دموية",
      categoryName: "جراحة أنف و أذن",
      rate: "4.5 / 5",
      numOfPatients: 300,
      price: 50,
      phone: 16777,
      info:
          " عضو الجمعية المصرية لطب الأطفال د. الزمالة البريطانية لطب الأطفال. دكتور اطفال وحديثي الولادة متخصص في اطفال و حديثي الولادة",
      address: "امام موقف شبين - المنوفية",
      city: "قويسنا",
      day: "السبت - الجمعة",
      time: "من الساعة 1 ظهراً"),
];
